package com.invincible


object CryptoData {

  case class Crypto(
                     name:String,
                     symbol:String,
                     price:Double,
                     displayName:String = "",
                     twentyFourHrChange:Double = 0,
                     marketCap:String = ""
                   ){
    def convertMarketCap:Long = Utils.convertDisplayNumber(marketCap)
  }
  case class CryptosArgs()
  case class CryptoArgs(symbol:String)

  val initializeCryptos = List(
    Crypto("Bitcoin","BTCUSD",23018.05),
    Crypto("Ether","ETHUSD",1646.17),
    Crypto("Tether","USDTUSD",1.00),
    Crypto("XRP","XRPUSD",0.39),
    Crypto("Cardano","ADAUSD",0.38),
    Crypto("Shiba Inu", "SHIBUSD", 0.00001),
    Crypto("Litecoin", "LTCUSD", 97.73),
    Crypto("Uniswap", "UNIUSD", 6.85),
    Crypto("Stellar", "XLMUSD", 0.09),
    Crypto("ApeCoin", "APEUSD", 5.74),
    Crypto("Wrapped Filecoin", "EFILUSD", 5.29),
    Crypto("Filecoin", "FILUSD", 5.29),
    Crypto("Lido DAO Token", "LDOUSD", 2.29),
    Crypto("Frax", "FRAXUSD", 0.99),
    Crypto("Frax Share", "FXSUSD", 10.10),
    Crypto("Chiliz", "CHZUSD", 0.14),
    Crypto("Immutable X", "IMXUSD", 0.93),
    Crypto("Enjin", "ENJUSD", 0.48, "Enjin Coin"),
    Crypto("Compound", "COMPUSD", 53.11),
    Crypto("STEPN", "GMTUSD", 0.52),
    Crypto("IoTeX", "IOTXUSD", 0.03),
    Crypto("SushiSwap", "SUSHIUSD", 1.50),
    Crypto("Ankr", "ANKRUSD", 0.02),
    Crypto("Amp", "AMPUSD", 0.004),
    Crypto("Livepeer", "LPTUSD", 9.18),
    Crypto("Dogelon Mars", "ELONUSD", 0.0000004),
    Crypto("Liquity USD", "LUSDUSD", 1.00),
    Crypto("Alethea Artificial Liquid Intelligence Token", "ALIUSD", 0.07, "Alethea Artificial Liquid Intelligence"),
    Crypto("Biconomy", "BICOUSD", 0.41),
    Crypto("Metis Token", "METISUSD", 37.67, "Metis"),
    Crypto("Ribbon Finance", "RBNUSD", 0.25),
    Crypto("KyberNetwork", "KNCUSD", 0.89,"Kyber Network"),
    Crypto("Merit Circle", "MCUSD", 0.39),
    Crypto("Numeraire", "NMRUSD", 22.89),
    Crypto("PlayDapp", "PLAUSD", 0.24),
    Crypto("KeepNetwork", "KEEPUSD", 0.20, "Keep Network"),
    Crypto("Wrapped Centrifuge", "WCFGUSD", 0.30),
    Crypto("Project Galaxy", "GALUSD", 2.28, "Galxe"),
    Crypto("Radicle", "RADUSD", 2.00),
    Crypto("Euler", "EULUSD", 5.26, "Euler Finance"),
    Crypto("Alchemy Pay", "ACHUSD", 0.01),
    Crypto("Bancor", "BNTUSD", 0.45),
    Crypto("Loom", "LOOMUSD", 0.05),
    Crypto("Orchid", "OXTUSD", 0.09),
    Crypto("Maple", "MPLUSD", 6.82),
    Crypto("TrueFi", "TRUUSD", 0.04),
    Crypto("Ethernity Chain", "ERNUSD", 2.42),
    Crypto("Keep3rV1", "KP3RUSD", 87.96),
    Crypto("Refereum", "RFRUSD", 0.006),
    Crypto("Bonfida", "FIDAUSD", 0.45),
    Crypto("DeFi Pulse Index", "DPIUSD", 89.39),
    Crypto("Goldfinch", "GFIUSD", 0.69),
    Crypto("Somnium Space", "CUBEUSD", 1.67),
    Crypto("Orca", "ORCAUSD", 1.07),
    Crypto("Samoyedcoin", "SAMOUSD", 0.004),
    Crypto("Cryptex", "CTXUSD", 2.70),
    Crypto("REVV", "REVVUSD", 0.01),
    Crypto("Geojam", "JAMUSD", 0.003),
    Crypto("tBTC", "tBTCUSD", 22384.00),
    Crypto("Saber", "SBRUSD", 0.001),
    Crypto("Total Crypto MarketCap", "TCAPUSD", 112.42, "Total Crypto Market Cap"),
    Crypto("Moss Carbon Credit", "MCO2USD", 2.07),
    Crypto("Burn", "ASHUSD", 1.10),
    Crypto("Wrapped TON Crystal", "WTONUSD", 0.06),
    Crypto("Zebec Protocol", "ZBCUSD", 0.01),
    Crypto("WrappedBitcoin", "WBTCUSD", 22829.26,"Wrapped Bitcoin"),
    Crypto("Yearn", "YFIUSD", 7695.76,"Yearn.finance"),
    Crypto("PAX Gold", "PAXGUSD", 1860.83),
    Crypto("Maker", "MKRUSD", 694.20),
    Crypto("Quant", "QNTUSD", 139.92),
    Crypto("Bitcoin Cash", "BCHUSD", 134.81),
    Crypto("Illuvium", "ILVUSD", 86.97),
    Crypto("Aave", "AAVEUSD", 86.39),
    Crypto("Zcash", "ZECUSD", 44.18),
    Crypto("Solana", "SOLUSD", 23.36),
    Crypto("Alchemix", "ALCXUSD", 21.27),
    Crypto("Avalanche", "AVAXUSD", 20.23),
    Crypto("WrappedNexusMutual", "WNXMUSD", 17.01,"Wrapped Nexus Mutual"),
    Crypto("Ethereum Name Service", "ENSUSD", 15.35),
    Crypto("Cosmos", "ATOMUSD", 14.50),
    Crypto("Axie Infinity", "AXSUSD", 11.00),
    Crypto("Chainlink", "LINKUSD", 7.00),
    Crypto("Balancer", "BALUSD", 7.00),
    Crypto("Polkadot", "DOTUSD", 6.67),
    Crypto("BarnBridge", "BONDUSD", 4.65),
    Crypto("Mask", "MASKUSD", 4.40),
    Crypto("Injective", "INJUSD", 3.55),
    Crypto("Synthetix", "SNXUSD", 2.73),
    Crypto("Uma", "UMAUSD", 2.09),
    Crypto("Render Token", "RNDRUSD", 1.91),
    Crypto("API3", "API3USD", 1.73),
    Crypto("Index Cooperative", "INDEXUSD", 1.66),
    Crypto("OMG Network", "OMGUSD", 1.56),
    Crypto("Polygon", "MATICUSD", 1.23),
    Crypto("Tezos", "XTZUSD", 1.18),
    Crypto("Magic Internet Money", "MIMUSD", 1.11),
    Crypto("Curve", "CRVUSD", 1.08),
    Crypto("EOS", "EOSUSD", 1.07),
    Crypto("Tokemak", "TOKEUSD", 1.04),
    Crypto("Dai", "DAIUSD", 1.00),
    Crypto("Binance USD", "BUSDUSD", 1.00),
    Crypto("USD Coin", "USDCUSD", 1.00),
    Crypto("gusd", "GUSDUSD", 1.00, "Gemini dollar"),
    Crypto("Decentraland", "MANAUSD", 0.73),
    Crypto("Sandbox", "SANDUSD", 0.72,"The Sandbox"),
    Crypto("Liquity", "LQTYUSD", 0.67),
    Crypto("1inch", "1INCHUSD", 0.56),
    Crypto("Fantom Ethereum", "FTMUSD", 0.55, "Fantom"),
    Crypto("DerivaDAO", "DDXUSD", 0.45),
    Crypto("Fetch ai", "FETUSD", 0.44,"Fetch.ai"),
    Crypto("Storj", "STORJUSD", 0.42),
    Crypto("Ocean", "OCEANUSD", 0.41),
    Crypto("Loopring", "LRCUSD", 0.37),
    Crypto("Audius", "AUDIOUSD", 0.32),
    Crypto("bat", "BATUSD", 0.28, "Basic Attention Token"),
    Crypto("Raydium", "RAYUSD", 0.27),
    Crypto("Golem", "GNTUSD", 0.25),
    Crypto("0x", "ZRXUSD", 0.24),
    Crypto("Qredo", "QRDOUSD", 0.20),
    Crypto("SuperRare", "RAREUSD", 0.17),
    Crypto("Graph", "GRTUSD", 0.13, "The Graph"),
    Crypto("Civic", "CVCUSD", 0.11),
    Crypto("Ren", "RENUSD", 0.09),
    Crypto("Dogecoin", "DOGEUSD", 0.09),
    Crypto("Gala", "GALAUSD", 0.05),
    Crypto("SKALE", "SKLUSD", 0.03),
    Crypto("Terrausd Ethereum", "USTUSD", 0.03, "TerraUSD"),
    Crypto("Rally", "RLYUSD", 0.01),
    Crypto("Bread", "BRDUSD", 0.008),
    Crypto("Smooth Love Potion", "SLPUSD", 0.003),
    Crypto("Caspian", "CSPUSD", 0.001),
    Crypto("Spell Token", "SPELLUSD", 0.0008, "Spell"),
    Crypto("Terra Ethereum", "LUNAUSD", 0.0001, "Terra"),
    Crypto("Mirror Ethereum", "MIRUSD", 0.00, "Mirror")
  )
}
